### ISSUE TITLE
Corrigir estilização da pesquisa de moteis do mapa e intregrar com backend

### ISSUE THREAD

**Issue by olucasfreitas** [geta-org/sex-adapt-mobile#77]
Nessa tarefa deve-se corrigir a estilização da pesquisa de motéis, para que ela funcione de forma correta e fique mais bonita, além de conectar a busca com os serviços do backend se necessário

- [x] Correção na esilização
- [x] Ao clicar, redirecionar para o motel selecionado
- [ ] Conecção com o backend (se necessário)

**Comment by ryanolivrdev** [comment]
-- Não necessário a conexão do backend
