### ISSUE TITLE
Integrações e correções na tela de detalhe do estabelecimento

### ISSUE THREAD

**Issue by olucasfreitas** [geta-org/sex-adapt-mobile#79]
Nessa tarefa, deve-se integrar tela de perfil com os serviços do backend

- [x] Integração das informações sobre o motel 
- [x] Integração do rating o motel nas estrelas
- [x] Integração do botão de favoritar com o backend
- [ ] Correção da estilização do componente das estrelas

**Comment by ryanolivrdev** [comment]
-- aguardando backend ( media do motel )

**Comment by ryanolivrdev** [comment]
As estrelas iram ficar com fundo branco e borda vermelha e quando estiverem preenchidas totalmente vermelha

**Comment by olucasfreitas** [comment]
bloqueado porquê precisamos passar o id do user na request
