### ISSUE TITLE
Tela de filtro

### ISSUE THREAD

**Issue by olucasfreitas** [geta-org/sex-adapt-mobile#84]
Nessa tarefa, deve-se corrigir a estilização da página inteira de estilos, além de se mudar o componente de slider para o slider do native base

- [x] mudar componente de slider para usar native base, e colocar calculo dentro do component
- [x] fix nos estilos
- [x] Integrar botão "aplicar" com o contexto dos motéis

**Comment by ryanolivrdev** [comment]
bloqueado porquê precisamos passar o id do user na request
